---
title: "GoT"
author: "Ruikun Xiao"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
```

```{r}
pacman::p_load(readr, data.table, tidyverse, readxl, rvest)
deaths = read_csv("character-deaths.csv")
deaths$`Book of Death`[157]=2
predictions = read_csv("character-predictions.csv")
deaths = data.table(deaths)
predictions = data.table(predictions)
colnames(deaths)[1]="name"
deaths = deaths[!(name=="Myles"&Allegiances=="House Tully")]
setkey(deaths, name)
setkey(predictions, name)
merged = merge(deaths, predictions)
merged
```

```{r}
charlist = read_excel("A Song of Ice and Fire Character Spreadsheet-2.xlsx",
                      sheet = "Characters")
charlist = data.table(charlist)
```

```{r}
males = c("Aggo","Del","Garth of Oldtown","Hamish the Harper","Luke of Longtown","Monster","Owen Norrey","Squint","Ulf the Ill","Wat (orphan)","Wat (sailor)","Will (orphan)","Wyl (guard)","Pate (Night's Watch)","Tim Tangletongue")
females = c("Joyeuse Erenford")
merged[name%in%males]$Gender=1
merged[name%in%males]$male=1
merged[name%in%females]$Gender=0
merged[name%in%females]$male=0
```

```{r}
gd_ck = function(name){
  loc = grep(name, charlist$Character)
  gd = unique(charlist$Gender[loc])
  if(length(gd)!=1) return(NA)
  if(gd=="M") return(1)
  if(gd=="F") return(0)
  return(-1)
}

ls_gd = as.integer(sapply(merged$name, gd_ck))

fixed_gd = ifelse(merged$Gender==merged$male, merged$Gender, ls_gd)

merged = cbind(merged, gender=fixed_gd)
```

```{r}
nb_ck = function(name){
  loc = grep(name, charlist$Character)
  nb = unique(!is.na(charlist$Title[loc]))
  if(length(nb)!=1) return(NA)
  return(as.integer(nb))
}

ls_nb = sapply(merged$name, nb_ck)

merged$Nobility[ls_nb==1]=1
merged$isNoble[ls_nb==1]=1
```









```{r}
merged[Nobility!=isNoble, .(name, Nobility, isNoble)]
```




```{r}
table(predictions$male)
table(deaths$Gender)
```


```{r}
diffgd = merged[Gender!=male, .(name, Gender, male)]
diffgd
```





```{r}
length(grep("House", merged$house))
unique(merged$house[-grep("House", merged$house)])
```

```{r}
houses = data.table(house_region)
houses$Region = str_split(houses$Region, " \\(") %>%
  lapply(head,1)%>%unlist()
houses$Region = str_split(houses$Region, ";") %>%
  lapply(head,1)%>%unlist()

grephouse = function(h){
  if(!grepl("House", h)) return(NA)
  return(substring(h,7))
}

house2region = function(h){
  h0 = grephouse(h)
  if(is.na(h0)) return(NA)
  if(grepl("of", h0)) return("Essos")
  if(h0=="Nymeros Martell") h0 = "Martell"
  matched = unique(houses[grep(h0,House),Region])
  if(length(matched)!=1) return("more_than_1")
  return(matched)
}

char_reg = sapply(merged$house, house2region)

wreg = merged[char_reg=="more_than_1",.(name, house)]

merged = cbind(merged, hs_reg=char_reg)
```


```{r}
house2regionlist = function(h){
  h0 = grephouse(h)
  if(is.na(h0)) return(NA)
  if(grepl("of", h0)) return("Essos")
  if(h0=="Nymeros Martell") h0 = "Martell"
  matched = unique(houses[grep(h0,House),Region])
  return(matched)
}

char_reg_ls = lapply(merged$house, house2regionlist)

save(char_reg_ls, file="char_reg_ls.RData")
```


```{r}
diffnb = merged[Nobility!=isNoble, .(name, Nobility, isNoble)]
checknb = lapply(diffnb$name, grep, ls_noble)%>%lapply(length)%>%unlist()
checknb2 = as.integer(diffnb$name%in%ls_noble)
diffnb = cbind(diffnb, checknb, checknb2)
diffnb[checknb!=checknb2]
```

```{r}
samenb = merged[Nobility==isNoble, .(name, Nobility)]
checknbs = lapply(samenb$name, grep, ls_noble)%>%lapply(length)%>%unlist()
checknb2s = as.integer(samenb$name%in%ls_noble)
samenb = cbind(samenb, checknbs, checknb2s)
samenb[Nobility!=checknb2s&checknbs==0]
```

```{r}
app_ls_nb = as.integer(merged$name%in%ls_noble)
corrected_nobility = as.integer((merged$Nobility*merged$isNoble)|app_ls_nb)
merged = cbind(merged, noble=corrected_nobility)
```





```{r}
samenb[Nobility!=checknb2s&checknb2s!=0]
```







```{r}
load("../data1201.RData")
data = data[!(name=="Myles"&Allegiances=="House Tully")]
data = cbind(data, noble = corrected_nobility)
saveRDS(data, file="../updated_data.rds")
```











```{r}
save(char_reg, file="char_reg.RData")
```



```{r}
save(merged, file="merged.Rdata")
```







